services:
  legal-bot:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: "2gb"
    container_name: advertisment-bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"

